env:
  global:
    secure: 9bdda66aef60357aa027281220b07603cac5384b
language: python
python:
  - "2.7"
before_install:
  - source .env
install:
  - pip install -U -r requirements.txt
script:
  - build 
after_success:
  - publish
