env:
  global:
    secure: 9bdda66aef60357aa027281220b07603cac5384b
language: python
python:
  - "2.7"
before_install:
  - source .env
install:
  - pip install -U -r requirements.txt
script:
  - remarkable --noinput remark cookiemonster.md "Cookie Monster"
after_success:
  - ghp-import -p cookie-monster; rm -rf cookie-monster
